// Generated by CoffeeScript 1.6.2
(function() {
  var Form1, Form2, Masks, Router, TBank, Validates, ViewClass, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref20, _ref21, _ref22, _ref23, _ref24, _ref25, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  Router = (function(_super) {
    __extends(Router, _super);

    function Router() {
      _ref = Router.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Router.prototype.routes = {
      '': 'first_form',
      'form2': 'second_form'
    };

    Router.prototype.first_form = function() {
      var model, view;

      model = new Form1;
      view = new ViewClass({
        model: model
      });
      return view.render();
    };

    Router.prototype.second_form = function() {
      var model;

      console.log("second_form");
      return model = new Form2;
    };

    return Router;

  })(Backbone.Router);

  $(function() {
    window.router = new Router;
    return Backbone.history.start();
  });

  TBank = {};

  TBank.cookieSync = function(method, model, options) {
    return console.log(method, model, options);
  };

  Backbone.Form = (function(_super) {
    __extends(Form, _super);

    function Form() {
      _ref1 = Form.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Form.prototype.schema = {};

    Form.prototype.defaults = function() {
      var attributes, key;

      attributes = {};
      for (key in this.schema) {
        attributes[key] = this.schema[key]['defaults'] || '';
      }
      return attributes;
    };

    Form.prototype.getValidators = function(key) {
      var validators;

      validators = [];
      if (this.schema[key]) {
        validators = this.schema[key]['validators'];
      }
      return validators;
    };

    Form.prototype.getMask = function(key) {
      if (this.schema[key]) {
        return this.schema[key]["mask"];
      }
    };

    Form.prototype.sync = function() {
      return TBank.cookieSync.apply(this, arguments);
    };

    return Form;

  })(Backbone.Model);

  Form1 = (function(_super) {
    __extends(Form1, _super);

    function Form1() {
      _ref2 = Form1.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Form1.prototype.schema = {
      maf_first_name: {
        validators: ['name']
      },
      maf_last_name: {
        validators: ['name']
      },
      maf_email: {
        validators: ['email']
      },
      maf_second_name: {
        validators: ['name']
      },
      maf_mobile_phone: {
        validators: ['phone'],
        mask: "phone"
      },
      maf_birth_date: {
        validators: ['date'],
        mask: "date"
      },
      maf_accept_rules: {
        validators: ['required']
      }
    };

    return Form1;

  })(Backbone.Form);

  Form2 = (function(_super) {
    __extends(Form2, _super);

    function Form2() {
      _ref3 = Form2.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    Form2.prototype.schema = {
      maf_zagran_fio: {
        validators: ['latinname']
      },
      maf_changed_fio: {
        validators: []
      },
      maf_passport_seria: {
        validators: ['pasportseria'],
        mask: "pasportseria"
      },
      maf_passport_number: {
        validators: ['pasportnumber'],
        mask: 'pasportnumber'
      },
      maf_passport_issue: {
        validators: ['name'],
        mask: 'date'
      },
      maf_passport_organisation: {
        validators: ['name']
      },
      maf_passport_code: {
        validators: ['name'],
        mask: 'pasportcode'
      },
      maf_birth_place: {
        validators: ['name']
      }
    };

    return Form2;

  })(Backbone.Form);

  Masks = {};

  Masks.Base = (function() {
    function Base($el) {
      $el.mask(this.mask);
    }

    return Base;

  })();

  Masks.Phone = (function(_super) {
    __extends(Phone, _super);

    function Phone() {
      _ref4 = Phone.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    Phone.prototype.mask = "+7 (999) 999-99-99";

    return Phone;

  })(Masks.Base);

  Masks.Date = (function(_super) {
    __extends(Date, _super);

    function Date() {
      _ref5 = Date.__super__.constructor.apply(this, arguments);
      return _ref5;
    }

    Date.prototype.mask = "99.99.9999";

    return Date;

  })(Masks.Base);

  Masks.Pasportseria = (function(_super) {
    __extends(Pasportseria, _super);

    function Pasportseria() {
      _ref6 = Pasportseria.__super__.constructor.apply(this, arguments);
      return _ref6;
    }

    Pasportseria.prototype.mask = "9999";

    return Pasportseria;

  })(Masks.Base);

  Masks.Pasportcode = (function(_super) {
    __extends(Pasportcode, _super);

    function Pasportcode() {
      _ref7 = Pasportcode.__super__.constructor.apply(this, arguments);
      return _ref7;
    }

    Pasportcode.prototype.mask = "999-999";

    return Pasportcode;

  })(Masks.Base);

  Validates = {};

  Validates.Base = (function() {
    function Base() {}

    Base.prototype.valid = function(value) {
      return this.regular.test(value);
    };

    return Base;

  })();

  Validates.Required = (function() {
    function Required() {}

    Required.prototype.valid = function(value) {
      return $.trim(value) !== '' && value;
    };

    return Required;

  })();

  Validates.Email = (function(_super) {
    __extends(Email, _super);

    function Email() {
      _ref8 = Email.__super__.constructor.apply(this, arguments);
      return _ref8;
    }

    Email.prototype.regular = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    return Email;

  })(Validates.Base);

  Validates.Name = (function(_super) {
    __extends(Name, _super);

    function Name() {
      _ref9 = Name.__super__.constructor.apply(this, arguments);
      return _ref9;
    }

    Name.prototype.regular = /^[а-яА-ЯёЁ\s-]{2,}$/;

    return Name;

  })(Validates.Base);

  Validates.Phone = (function(_super) {
    __extends(Phone, _super);

    function Phone() {
      _ref10 = Phone.__super__.constructor.apply(this, arguments);
      return _ref10;
    }

    Phone.prototype.regular = /^\+\d\s\([\d]{3}\)\s[\d]{3}\-[\d]{2}\-[\d]{2}$/;

    return Phone;

  })(Validates.Base);

  Validates.Date = (function(_super) {
    __extends(Date, _super);

    function Date() {
      _ref11 = Date.__super__.constructor.apply(this, arguments);
      return _ref11;
    }

    Date.prototype.regular = /^[\d]{2}\.[\d]{2}\.[\d]{4}$/;

    return Date;

  })(Validates.Base);

  Validates.Country = (function(_super) {
    __extends(Country, _super);

    function Country() {
      _ref12 = Country.__super__.constructor.apply(this, arguments);
      return _ref12;
    }

    Country.prototype.regular = /^[а-яА-ЯёЁ\,\s]{3,}[\s\,а-яА-ЯёЁ]+$/;

    return Country;

  })(Validates.Base);

  Validates.Latinname = (function(_super) {
    __extends(Latinname, _super);

    function Latinname() {
      _ref13 = Latinname.__super__.constructor.apply(this, arguments);
      return _ref13;
    }

    Latinname.prototype.regular = /^[a-zA-Z-]{3,}\s[a-zA-Z-]{3,}$/;

    return Latinname;

  })(Validates.Base);

  Validates.Pasportseria = (function(_super) {
    __extends(Pasportseria, _super);

    function Pasportseria() {
      _ref14 = Pasportseria.__super__.constructor.apply(this, arguments);
      return _ref14;
    }

    Pasportseria.prototype.regular = /^[\d]{2}-?\s?[\d]{2}$/;

    return Pasportseria;

  })(Validates.Base);

  Validates.Pasportnumber = (function(_super) {
    __extends(Pasportnumber, _super);

    function Pasportnumber() {
      _ref15 = Pasportnumber.__super__.constructor.apply(this, arguments);
      return _ref15;
    }

    Pasportnumber.prototype.regular = /^\d{6}$/;

    return Pasportnumber;

  })(Validates.Base);

  Validates.Pasportcode = (function(_super) {
    __extends(Pasportcode, _super);

    function Pasportcode() {
      _ref16 = Pasportcode.__super__.constructor.apply(this, arguments);
      return _ref16;
    }

    Pasportcode.prototype.regular = /^\d{3}-?\d{3}$/;

    return Pasportcode;

  })(Validates.Base);

  Validates.Simpletext = (function(_super) {
    __extends(Simpletext, _super);

    function Simpletext() {
      _ref17 = Simpletext.__super__.constructor.apply(this, arguments);
      return _ref17;
    }

    Simpletext.prototype.regular = /^[а-яА-ЯёЁ№0-9,\.\'\"\-\«\»\—\s]{3,}$/;

    return Simpletext;

  })(Validates.Base);

  Validates.Commontext = (function(_super) {
    __extends(Commontext, _super);

    function Commontext() {
      _ref18 = Commontext.__super__.constructor.apply(this, arguments);
      return _ref18;
    }

    Commontext.prototype.regular = /^[a-zA-Zа-яА-ЯёЁ№0-9,\.\'\"\-\«\»\—\s]{3,}$/;

    return Commontext;

  })(Validates.Base);

  Validates.Anytext = (function(_super) {
    __extends(Anytext, _super);

    function Anytext() {
      _ref19 = Anytext.__super__.constructor.apply(this, arguments);
      return _ref19;
    }

    Anytext.prototype.regular = /^.{3,}$/;

    return Anytext;

  })(Validates.Base);

  Validates.Adress = (function(_super) {
    __extends(Adress, _super);

    function Adress() {
      _ref20 = Adress.__super__.constructor.apply(this, arguments);
      return _ref20;
    }

    Adress.prototype.regular = /^[а-яА-Я\.\(\)\s-,0-9]{3,}$/;

    return Adress;

  })(Validates.Base);

  Validates.Adressnum = (function(_super) {
    __extends(Adressnum, _super);

    function Adressnum() {
      _ref21 = Adressnum.__super__.constructor.apply(this, arguments);
      return _ref21;
    }

    Adressnum.prototype.regular = /^[а-яА-Яa-zA-Z\/\(\)\s-,0-9]{1,}$/;

    return Adressnum;

  })(Validates.Base);

  Validates.Number = (function(_super) {
    __extends(Number, _super);

    function Number() {
      _ref22 = Number.__super__.constructor.apply(this, arguments);
      return _ref22;
    }

    Number.prototype.regular = /^\d{3,}$/;

    return Number;

  })(Validates.Base);

  Validates.Codeword = (function(_super) {
    __extends(Codeword, _super);

    function Codeword() {
      _ref23 = Codeword.__super__.constructor.apply(this, arguments);
      return _ref23;
    }

    Codeword.prototype.regular = /^[а-яА-Я]{3,}$/;

    return Codeword;

  })(Validates.Base);

  Validates.Checkcode = (function(_super) {
    __extends(Checkcode, _super);

    function Checkcode() {
      _ref24 = Checkcode.__super__.constructor.apply(this, arguments);
      return _ref24;
    }

    Checkcode.prototype.regular = /^\d{5}$/;

    return Checkcode;

  })(Validates.Base);

  ViewClass = (function(_super) {
    __extends(ViewClass, _super);

    function ViewClass() {
      _ref25 = ViewClass.__super__.constructor.apply(this, arguments);
      return _ref25;
    }

    ViewClass.prototype._modelBinder = void 0;

    ViewClass.prototype.events = {
      "click #first_step_submit": "commit"
    };

    ViewClass.prototype.initialize = function() {
      _.bindAll(this);
      return this._modelBinder = new Backbone.ModelBinder;
    };

    ViewClass.prototype.render = function() {
      var key, mask;

      this.setElement($(".formBlock1"));
      this._modelBinder.bind(this.model, this.el);
      for (key in this.model.attributes) {
        if (mask = this.model.getMask(key)) {
          eval("new Masks." + (mask.capitalize()) + "( $('#" + key + "') )");
        }
      }
      return this;
    };

    ViewClass.prototype.commit = function() {
      console.log(this.model.toJSON());
      if (1) {
        console.log('commit');
        this.model.save();
        router.navigate("form2", {
          trigger: true
        });
        return $("#test-content").html(JSON.stringify(this.model.toJSON()));
      }
    };

    ViewClass.prototype.validate = function() {
      var key, valid;

      valid = true;
      for (key in this.model.attributes) {
        valid = this.validatefield(key) && valid;
      }
      return valid;
    };

    ViewClass.prototype.validatefield = function(key) {
      var valid, validator, validators, value, _i, _len;

      valid = true;
      value = this.model.get(key);
      validators = this.model.getValidators(key);
      for (_i = 0, _len = validators.length; _i < _len; _i++) {
        validator = validators[_i];
        validator = eval("new Validates." + (validator.capitalize()));
        valid && (valid = validator.valid(value));
        if (valid) {
          this.clearError(key);
        } else {
          this.setError(key);
        }
      }
      return valid;
    };

    ViewClass.prototype.setError = function(key) {
      var $label;

      $label = $("#" + key + "_label");
      if ($label.length) {
        return $label.addClass("accessError");
      } else {
        return $("#" + key).parent().addClass('textfieldError');
      }
    };

    ViewClass.prototype.clearError = function(key) {
      var $label;

      $label = $("#" + key + "_label");
      if ($label.length) {
        return $label.removeClass("accessError");
      } else {
        return $("#" + key).parent().removeClass('textfieldError');
      }
    };

    return ViewClass;

  })(Backbone.View);

  $(function() {
    return $("input").each(function() {
      var $this;

      $this = $(this);
      return $this.attr("placeholder", $this.attr("hint"));
    });
  });

  $(function() {
    var Item, ItemView, List, ListView, testView, _ref26, _ref27, _ref28, _ref29;

    Item = (function(_super) {
      __extends(Item, _super);

      function Item() {
        _ref26 = Item.__super__.constructor.apply(this, arguments);
        return _ref26;
      }

      Item.prototype.defaults = {
        part1: "Hello",
        part2: "Backbone"
      };

      return Item;

    })(Backbone.Model);
    List = (function(_super) {
      __extends(List, _super);

      function List() {
        _ref27 = List.__super__.constructor.apply(this, arguments);
        return _ref27;
      }

      List.prototype.model = Item;

      return List;

    })(Backbone.Collection);
    ItemView = (function(_super) {
      __extends(ItemView, _super);

      function ItemView() {
        this.unrender = __bind(this.unrender, this);
        this.render = __bind(this.render, this);        _ref28 = ItemView.__super__.constructor.apply(this, arguments);
        return _ref28;
      }

      ItemView.prototype.tagName = "li";

      ItemView.prototype.initialize = function() {
        _.bindAll(this);
        this.model.bind("change", this.render);
        return this.model.bind("remove", this.unrender);
      };

      ItemView.prototype.render = function() {
        $(this.el).html("<span>" + (this.model.get('part1')) + " " + (this.model.get('part2')) + "</span>\n<span class='swap'>swap</span>\n<span class='delete'>delete</span>");
        return this;
      };

      ItemView.prototype.unrender = function() {
        return $(this.el).remove();
      };

      ItemView.prototype.swap = function() {
        return this.model.set({
          part1: this.model.get("part2"),
          part2: this.model.get("part1")
        });
      };

      ItemView.prototype.remove = function() {
        return this.model.destroy();
      };

      ItemView.prototype.events = {
        "click .swap": "swap",
        "click .delete": "remove"
      };

      return ItemView;

    })(Backbone.View);
    ListView = (function(_super) {
      __extends(ListView, _super);

      function ListView() {
        _ref29 = ListView.__super__.constructor.apply(this, arguments);
        return _ref29;
      }

      ListView.prototype.el = $("body");

      ListView.prototype.initialize = function() {
        _.bindAll(this);
        this.collection = new List;
        this.collection.bind("add", this.appendItem);
        this.counter = 0;
        return this.render();
      };

      ListView.prototype.render = function() {
        $(this.el).append("<button class='btn'>Add List Item</button>");
        return $(this.el).append("<ul></ul>");
      };

      ListView.prototype.addItem = function() {
        var item;

        this.counter++;
        item = new Item;
        item.set({
          part2: "" + (item.get('part2')) + " " + this.counter
        });
        return this.collection.add(item);
      };

      ListView.prototype.appendItem = function(item) {
        var item_view;

        item_view = new ItemView({
          model: item
        });
        return $("ul").append(item_view.render().el);
      };

      ListView.prototype.events = {
        "click button": "addItem"
      };

      return ListView;

    })(Backbone.View);
    Backbone.sync = function(method, model, success, error) {
      return success();
    };
    return testView = new ListView;
  });

}).call(this);
