// Generated by CoffeeScript 1.6.2
(function() {
  var Form1, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Form1 = (function(_super) {
    __extends(Form1, _super);

    function Form1() {
      _ref = Form1.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Form1.prototype.schema = {
      maf_first_name: {
        validators: ['required']
      },
      maf_last_name: {
        validators: ['required']
      },
      maf_email: {
        validators: ['email']
      },
      maf_second_name: {
        validators: ['required']
      },
      maf_mobile_phone: {
        validators: ['required']
      },
      maf_birth_date: {
        validators: ['required']
      },
      maf_accept_rules: {
        validators: ['required']
      }
    };

    return Form1;

  })(Backbone.Form);

}).call(this);
