// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var ViewClass, model, view, _ref;

    model = new Backbone.Model({
      name: "Edvatd"
    });
    model.bind("change", function() {
      return $("#test-content").html(JSON.stringify(model.toJSON()));
    });
    model.trigger("change");
    ViewClass = (function(_super) {
      __extends(ViewClass, _super);

      function ViewClass() {
        _ref = ViewClass.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ViewClass.prototype._modelBinder = void 0;

      ViewClass.prototype.initialize = function() {
        return this._modelBinder = new Backbone.ModelBinder;
      };

      ViewClass.prototype.render = function() {
        this.setElement("#maf_first_name");
        console.log(this._modelBinder);
        this._modelBinder.bind(this.model, this.el);
        return this;
      };

      ViewClass.prototype.set_log = function() {
        console.log(111);
        return console.log(this.model.set("name", this.$el.val()));
      };

      return ViewClass;

    })(Backbone.View);
    view = new ViewClass({
      model: model
    });
    return console.log(view.render());
  });

}).call(this);
