// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var ViewClass, model, view, _ref;

    model = new Backbone.Model({
      maf_last_name: "",
      maf_first_name: "",
      maf_second_name: ""
    });
    model.bind("change", function() {
      return $("#test-content").html(JSON.stringify(model.toJSON()));
    });
    model.trigger("change");
    ViewClass = (function(_super) {
      __extends(ViewClass, _super);

      function ViewClass() {
        _ref = ViewClass.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ViewClass.prototype._modelBinder = void 0;

      ViewClass.prototype.initialize = function() {
        return this._modelBinder = new Backbone.ModelBinder;
      };

      ViewClass.prototype.render = function() {
        this.setElement($(".formBlock1"));
        this._modelBinder.bind(this.model, this.el);
        return this;
      };

      return ViewClass;

    })(Backbone.View);
    view = new ViewClass({
      model: model
    });
    return console.log(view.render());
  });

}).call(this);
