// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    return $("input").each(function() {
      var $this;

      $this = $(this);
      return $this.attr("placeholder", $this.attr("hint"));
    });
  });

}).call(this);
