// Generated by CoffeeScript 1.6.2
(function() {
  var Validates;

  Validates = {};

  Validates.Required = (function() {
    function Required() {}

    Required.prototype.valid = function(value) {
      return value !== '' && value;
    };

    return Required;

  })();

  Validates.Email = (function() {
    function Email() {}

    Email.prototype.valid = function(value) {
      return /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i.test(value);
    };

    return Email;

  })();

}).call(this);
